# Generated by Django 4.2.5 on 2023-10-21 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_generate_recepts_ingridents'),
    ]

    operations = [
        migrations.AddField(
            model_name='generate_recepts',
            name='img',
            field=models.ImageField(null=True, upload_to='ai'),
        ),
        migrations.AddField(
            model_name='recepts',
            name='img',
            field=models.ImageField(null=True, upload_to='recepts'),
        ),
    ]
