# Generated by Django 4.2.5 on 2023-10-22 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_generate_recepts_img_recepts_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='recepts',
            name='time',
            field=models.CharField(choices=[('breakfast', 'breakfast'), ('lunch', 'lunch'), ('dinner', 'dinner')], max_length=255, null=True),
        ),
    ]
