# Generated by Django 4.2.5 on 2023-10-22 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_recepts_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generate_recepts',
            name='img',
        ),
    ]
